Import api and filter api tests
ONSdigital/dp-api-tests pull request #1
Opened 2017-10-02 14:56 UTC by pathimanoj

### What

Added Import api and filter api tests.
There are 2 tests failing in import api and bugs are raised for those.
There are 3 tests failing in import api and bugs are raised for those.

### How to review

Run the tests and review the code.

### Who can review

Anyone.

2017-10-03 10:32 UTC, CarlHembrough commented on config/config.go
> +	return "http://localhost:22100"
These values will need to be configurable - see the pattern used in other cmd repos: https://github.com/ONSdigital/dp-observation-importer/blob/cmd-develop/config/config.go

2017-10-03 10:41 UTC, CarlHembrough commented
Consider taking out the httpexpect directory, and just have the service name directories at the root of the repo.

2017-10-03 10:42 UTC, CarlHembrough commented
govendor needs running to pull in addional dependencies. See https://github.com/kardianos/govendor and ask any questions 👍

2017-10-03 11:43 UTC, CarlHembrough requested changes
Looks good overall. I have added a few comments. I would suggest using a consistent 'given, when, then' structure for documenting tests to improve their readability. This will also improve the reporting.

2017-10-23 09:11 UTC, nshumoogum commented
This PR has been superceded by other branches and pull requests

2017-10-23 09:11 UTC, nshumoogum commented
This PR has been superceded by other branches and pull requests

2017-10-23 09:11 UTC, closed without merging