Feature/editions
ONSdigital/dp-api-tests pull request #96
Opened 2018-07-05 07:21 UTC by mattrout92

### What

Describe what you have changed and why.

### How to review

Describe the steps required to test the changes.

### Who can review

Describe who worked on the changes, so that other people can review.

2018-07-06 12:15 UTC, eldeal requested changes

2018-07-06 12:15 UTC, eldeal commented on codeListAPI/get_edition_test.go
> +	Convey("Given an edition of a codelist eqists", t, func() {
exists doesn't have a q in it :)

2018-07-06 12:15 UTC, eldeal commented on codeListAPI/get_edition_test.go
> +				response.Value("id").Equal("ABCDEF")
I'm not certain we should be returning ID as the code list name here. not sure ID is a meaningful field for this endpoint.

2018-07-06 12:15 UTC, eldeal commented on codeListAPI/get_edition_test.go
> +				codelistAPI.GET("/code-lists/ABCDEF/editions/2019").Expect().Status(http.StatusNotFound)
Feels like 'an edition of a code list which doesnt exist' and 'an edition which doesnt exist of a code list that does' should be different test cases to more easily determine possible failures in future

2018-07-06 12:15 UTC, eldeal commented on codeListAPI/get_editions_test.go
> +			Convey("Then the codelists are returned to the user", func() {
the editions are returned to the user, rather than codelists, as there's only one list at this point?

2018-07-12 09:34 UTC, CarlHembrough approved these changes
LGTM - we will need to revisit this when the data model is updated

2018-07-12 09:37 UTC, merged